package com.tcon.webid.controller;

import com.tcon.webid.service.MailService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/internal")
public class MailTestController {

    private static final Logger log = LoggerFactory.getLogger(MailTestController.class);

    @Autowired
    private MailService mailService;

    @PostMapping("/test-email")
    public ResponseEntity<String> sendTestEmail(@RequestParam(required = false) String to,
                                                @RequestParam(required = false) String subject,
                                                @RequestParam(required = false) String body) {
        String target = (to == null || to.isBlank()) ? "info@tconsolutions.com" : to;
        String subj = (subject == null || subject.isBlank()) ? "Test Email from Event Bidding" : subject;
        String b = (body == null || body.isBlank()) ? "This is a test email generated by the application to verify SMTP settings." : body;

        try {
            log.info("Triggering test email to={}", target);
            mailService.sendSimpleMail(target, subj, b);
            return ResponseEntity.ok("Test email send attempted to: " + target);
        } catch (Exception e) {
            log.error("Test email failed", e);
            return ResponseEntity.status(500).body("Test email failed: " + e.getMessage());
        }
    }
}


